conditions: v1

dist: xenial
language: python

python:
- pypy3

jobs:
  fast_finish: true
  include:
  - python: pypy
    env:
      PYTEST_ADDOPTS: >-
        '-p no:warnings'

cache:
  pip: true
  directories:
  - $HOME/.cache/pre-commit
  - $HOME/.pre-commit
  - $HOME/virtualenv/python$(python -c 'import platform; print(platform.python_version())')

install:
- python -m pip install --upgrade virtualenv
- python -m pip install tox
- python -m tox --notest  # Pre-populate a virtualenv with dependencies
- >-
  python -c 'import ssl; print("\nOPENSSL_VERSION: " + ssl.OPENSSL_VERSION + "\nOPENSSL_VERSION_INFO: " + repr(ssl.OPENSSL_VERSION_INFO) + "\nOPENSSL_VERSION_NUMBER: " + repr(ssl.OPENSSL_VERSION_NUMBER))'
- >-
  ".tox/${TOXENV:-python}/bin/python" -m OpenSSL.debug || true

script:
- python -m tox

after_failure:
- ip a
- sysctl -a
- echo "Here's a list of installed Python packages:"
- pip list --format=columns
- echo Dumping logs, because tests failed to succeed
- |
    for log in `ls cheroot/test/*.log`
    do
      echo Outputting $log
      cat $log
    done
- py_log=/home/travis/build/cherrypy/cheroot/.tox/python/log/python-0.log
- echo Outputting python invocation log from $py_log
- cat $py_log
