sudo: false
language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
# disabled per https://github.com/cherrypy/cheroot/issues/21
# - pypy
- pypy3
- nightly
_base_envs:
- &pypy_base
  python: pypy
  env:
  - PYPY_VERSION=pypy2-5.7.1
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  dist: trusty
  sudo: required
  addons:
    apt:
      packages:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
  before_install:
  - |
    if [ -f "$PYENV_ROOT/bin/pyenv" ]
    then
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv update
    else
      rm -rf "$PYENV_ROOT"
      curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    fi
    pyenv install --skip-existing --keep --verbose "$PYPY_VERSION"
    pyenv shell "$PYPY_VERSION"
    python --version
matrix:
  fast_finish: true
  allow_failures:
  - env: TOXENV=pre-commit-pep257
  - python: pypy3
    env: PYPY_VERSION=pypy3.5-5.7.1-beta
  include:
  - <<: *pypy_base
    python: pypy
    env:
    - PYPY_VERSION=pypy2-5.7.1
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
    - <<: *pypy_base
      python: pypy3
      env:
      - PYPY_VERSION=pypy3.5-5.7.1-beta
      - PYENV_ROOT="$HOME/.pyenv"
      - PATH="$PYENV_ROOT/bin:$PATH"
  - python: 3.6
    env: TOXENV=pre-commit
  - python: 3.6
    env: TOXENV=pre-commit-pep257
cache:
  pip: true
  directories:
  - $HOME/.pre-commit
before_install:
- "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then . .travis/replace-pypy3 ; fi"
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: RAfz06AINvz7bfij/YhfkAreRqamgxS8a6jSRNxntYhtJke3ZszUbIDag8+n1I+G5XT2LnMhHqPNR7Plc+AeMz7VXTuy+b81Li5kse20NYlPhd7mBVmTUpXtqYQashV5J39F4qkATBLznCOrMEomM07VTXjO/o2hmQuXniab2Uo=
