conditions: v1

dist: xenial
language: python

python:
- 2.7
- 3.4
- 3.5
- 3.6
- &pypy3 pypy3

_base_envs:
- &stage_test_priority
  stage: &stage_test_priority_name test against latest Python versions first (under GNU/Linux)
- &stage_deploy
  stage: &stage_deploy_name upload new version of python package to PYPI (only for tagged commits)

jobs:
  fast_finish: true
  include:
  - python: pypy
    env:
      PYTEST_ADDOPTS: >-
        '-p no:warnings'
  - <<: *stage_test_priority
    python: 3.8
  - <<: *stage_test_priority
    python: 3.7
  - <<: *stage_deploy
    if: tag IS present
    python: 3.7
    install:
    - python -m pip install --upgrade virtualenv
    - python -m pip install tox
    env:
      TOXENV: release

cache:
  pip: true
  directories:
  - $HOME/.cache/pre-commit
  - $HOME/.pre-commit
  - $HOME/virtualenv/python$(python -c 'import platform; print(platform.python_version())')

install:
- python -m pip install --upgrade virtualenv
- python -m pip install tox
- python -m tox --notest  # Pre-populate a virtualenv with dependencies
- >-
  python -c 'import ssl; print("\nOPENSSL_VERSION: " + ssl.OPENSSL_VERSION + "\nOPENSSL_VERSION_INFO: " + repr(ssl.OPENSSL_VERSION_INFO) + "\nOPENSSL_VERSION_NUMBER: " + repr(ssl.OPENSSL_VERSION_NUMBER))'
- >-
  ".tox/${TOXENV:-python}/bin/python" -m OpenSSL.debug || true

script:
- python -m tox

after_failure:
- ip a
- sysctl -a
- echo "Here's a list of installed Python packages:"
- pip list --format=columns
- echo Dumping logs, because tests failed to succeed
- |
    for log in `ls cheroot/test/*.log`
    do
      echo Outputting $log
      cat $log
    done
- py_log=/home/travis/build/cherrypy/cheroot/.tox/python/log/python-0.log
- echo Outputting python invocation log from $py_log
- cat $py_log
stages:
- *stage_test_priority_name
- name: *stage_deploy_name
