language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6-dev
- pypy
- pypy3
- nightly

matrix:
  fast_finish: true
  allow_failures:
    # TODO: check what causes testing stuck
    - python: pypy
    # TODO: fix tests
    - python: pypy3
    - env: TOXENV=pre-commit
  include:
    - python: 3.5
      env: TOXENV=pre-commit

cache: pip

install: pip install tox
script: tox

deploy:
  provider: pypi
  on:
    tags: true
    python: 3.5
  user: jaraco
  distributions: release
  skip_upload_docs: true
