---

name: pip-tools

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
  - cron: 1 0 * * *  # Run daily at 0:01 UTC

concurrency:
  group: >-
    ${{
        github.workflow
    }}-${{
        github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:

  deps:
    name: >-
      ⛓🔒 🐍${{
          matrix.python-version
      }} @ ${{
          matrix.os
      }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
        # NOTE: The latest and the lowest supported Pythons are prioritized
        # NOTE: to improve the responsiveness. It's nice to see the most
        # NOTE: important results first.
        - >-
          3.10
        - pypy2
        - 3.9
        - 3.8
        - pypy-3.7
        - 3.7
        - 3.6
        - 3.5
        - 2.7
        - 3.11.0-alpha - 3.11.0
        - pypy-3.6
        os:
        - ubuntu-18.04
        - macOS-11.0
        - windows-2016
        exclude:
        # NOTE: macOS PyPy 3.6 job is excluded because during
        # NOTE: self-provisioning, invoking `ensurepip` fails to load
        # NOTE: some CFFI libs with a traceback saying
        # NOTE: `AttributeError: No symbol SCDynamicStoreCopyProxies
        # NOTE: found in library <None>`
        - os: macOS-11.0
          python-version: pypy-3.6
        include:
        # NOTE: The only GNU/Linux CPython 3.4 available is built for Ubuntu 18
        # https://github.com/actions/python-versions/blob/c483657/versions-manifest.json#L1228
        - os: ubuntu-18.04
          python-version: 3.4

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_PYTHON_VERSION_WARNING: 1
      PIP_NO_WARN_SCRIPT_LOCATION: 1
      PY_COLORS: 1

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip with `requires_python`
      run: >-
        python -m
        pip install
        --user
        --upgrade
        --force-reinstall
        pip-with-requires-python
    - name: Install pip-tools
      run: >-
        python -m
        pip install
        --user
        pip-tools

    - name: Grab the source from Git
      uses: actions/checkout@v2

    - name: Generate constraints files
      run: >
        BASE_NAME=$(
        PYTHONPATH=bin/ python -c
        'from pip_constraint_helpers import get_constraint_file_path,
        get_runtime_python_tag;
        print(get_constraint_file_path(
        "", "py", get_runtime_python_tag())[:-4]
        )
        '
        )


        (cd requirements/; ln -svf tests.in "${BASE_NAME}.in")


        python -m piptools compile
        --allow-unsafe
        --output-file="requirements/${BASE_NAME}.txt"
        ${{
        (
        matrix.python-version != '2.7'
        && matrix.python-version != '3.4'
        && matrix.python-version != '3.5'
        && matrix.python-version != 'pypy2'
        )
        && '--strip-extras'
        || ''
        }}
        "requirements/${BASE_NAME}.in"
      shell: bash

  check:  # This job does nothing and is only used for the branch protection
    if: always()

    needs:
    - deps

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  publish-pr:
    name: Publish 🐍📦 ${{ needs.pre-setup.outputs.git-tag }} to PyPI
    needs:
    - check
    - pre-setup  # transitive, for accessing settings
    if: >-
      fromJSON(needs.pre-setup.outputs.release-requested)
    runs-on: Ubuntu-latest

    environment: pip-tools

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v2
      with:
        name: python-package-distributions
        path: dist/
    - name: >-
        Publish 🐍📦 ${{ needs.pre-setup.outputs.git-tag }} to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PIP_TOOLS_DEPLOYMENT_KEY }}

  post-release-repo-update:
    name: >-
      Publish post-release Git tag
      for ${{ needs.pre-setup.outputs.git-tag }}
    needs:
    - publish-pypi
    - pre-setup  # transitive, for accessing settings
    runs-on: Ubuntu-latest

    steps:
    - name: Fetch the src snapshot
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: ${{ github.event.inputs.release-commitish }}
    - name: Setup git user as [bot]
      uses: fregante/setup-git-user@v1.0.1

    - name: >-
        Tag the release in the local Git repo
        as v${{ needs.pre-setup.outputs.git-tag }}
      run: >-
        git tag
        -m '${{ needs.pre-setup.outputs.git-tag }}'
        '${{ needs.pre-setup.outputs.git-tag }}'
        --
        ${{ github.event.inputs.release-commitish }}
    - name: >-
        Push ${{ needs.pre-setup.outputs.git-tag }} tag corresponding
        to the just published release back to GitHub
      run: >-
        git push --atomic origin '${{ needs.pre-setup.outputs.git-tag }}'

...
